### ISSUE TITLE
feature idea - support folders mounted over `ssh` / via `sshfs`

### ISSUE THREAD

**Issue by evandrix** [joowani/dtags#1]
that would be cool to have for automation's sake, from a sysadmin's PoV

**Comment by joowani** [comment]
Hi evandrix,

Although dtags does not automount or manage /etc/fstab, it _does_ handle mounted directories over ssh. Was there any particular command that is failing for you? 

Jay

**Comment by joowani** [comment]
Hi evandrix,

I haven't heard back from you so I am just going to close this issue for now.
If you have any specific command that's failing with directories mounted via ssh feel free to reopen this issue with the details.

Thanks!
