### ISSUE TITLE
Quieter directory command

### ISSUE THREAD

**Issue by acrisci** [joowani/dtags#10]
According to the README, the directory command (`d`) can be used as a replacement for `cd`.

I would like to try that, but I would like it to be a bit quieter similar to `cd`. I don't want it to announce what directory I am going to. This is in line with the Unix philosophy of avoiding cluttering output with extraneous information.

I do see benefit in announcing what directory it will change to when an alias is given. This follows the principle of least astonishment, because it might even be ambiguous sometimes what my intentions are, if for instance there is a directory with the same name as my directory alias in the cwd.

So I would like it to not print the directory when using it like `cd` in the normal way (not going to a tagged directory) and only print the directory name when going to a tag.

Otherwise, I would like a `--quiet` flag that could disable the output entirely when changing directories.

Thanks.

**Comment by joowani** [comment]
Hi acrisci,

Good point. Instead of a `--quiet` flag, however, I will disable the announcement by default and add a flag `--verbose` which will then display the full path.

Thanks,
Jay

**Comment by joowani** [comment]
Hi again,

I've removed the ``Going to`` message completely. As for the principle of least astonishment, I've decided to instead clearly specify in the technical notes section in the README that if there is a name conflict, the tag is preferred over the subdirectory (and that you can put ``/`` at the end of the subdirectory name if you want to go to it).

Thanks for your input.
Jay

**Comment by acrisci** [comment]
:+1:
