### ISSUE TITLE
Refactor scripts into template files

### ISSUE THREAD

**Issue by acrisci** [joowani/dtags#13]
Right now, the scripts are hard to read and modify because we don't get syntax highlighting or other editor features. Refactoring them into proper template files would be helpful for modifying the scripts.

[Mustache](https://mustache.github.io/mustache.5.html) templates would be a good choice. Another simple option would be to use `%VARIABLE%` for variables and then do a simple search and replace.

**Comment by joowani** [comment]
Yes it is a bit painful to edit and debug the shell code. Right now, however, dtags has 0 package dependencies and I really would like to keep it that way. I will consider templates if the shell code grows more. I don't think it's too bad right now.

**Comment by joowani** [comment]
For now I will be closing this issue as this does not seem to be critical. Thanks.
