### ISSUE TITLE
Command to make other commands work with dtags

### ISSUE THREAD

**Issue by acrisci** [joowani/dtags#14]
Now that I'm using dtags, I'm getting kind of spoiled by the convenience of my `cd` command and I want the convenience for my other commands too for common shell operations.

For instance, if I want to copy a file from one of my tagged directories, I would like to do this

    cp my-tagged-dir/some-file ./

To make this happen, I would like a command called `expand` that can be used to accept a list of directories, and then print the list but with the tags expanded. Then I could do this:

```bash
dtags-cp() {
    cp $(dtags expand $@)
}
```

If a tag is not found, simply leave it alone.

It would be nice if there was an automated way to do that with every command, but I can't think of how to do that since many commands can accept mixed input of commands and directories and it's hard to tell exactly which is which.

**Comment by joowani** [comment]
I am actually implementing a new feature which achieves something similar to what you are asking.
When a user tags a directory, and there is a 1-to-1 mapping between the directory and the tag (i.e. no other directories have the same tag), and the name of the tag does not conflict with environment variables, dtags will create an shell variable for you to use. For example:

```
~$ tag ~/foo
~$ d foo
~$ e foo ls -l
~$ cd $foo
~$ cp $foo/file.py ~/
```

Would that work for you?

**Comment by acrisci** [comment]
I think that would be ok for my use case. You might want to consider adding a prefix to the variables to avoid conflicts though :+1:

**Comment by joowani** [comment]
https://github.com/joowani/dtags/releases/tag/3.0.0 with the new feature is now released! Please try it out! 

I've considered appending a prefix. For sake of simplicity I'll leave it up to the users to pick the right tag names that won't conflict with whatever variables they may already have defined. If I get complaints then I will reconsider. Thanks!
