### ISSUE TITLE
Only alphabets and the underscore character are now allowed in tag names

### ISSUE THREAD

**Issue by egeerardyn** [joowani/dtags#15]
Is there a reason why other characters (e.g. I have some tags with numbers in them) are no longer supported? If not, could numbers be re-allowed?

**Comment by joowani** [comment]
Hi egeerardyn,

There was an error in the release notes which is now corrected. Numbers ARE still allowed, but some characters like the hyphen had to be removed to support the new shell variables feature (as variable names are more restrictive and do not allow hyphens). Sorry for the confusion.

**Comment by egeerardyn** [comment]
That's great to hear. 👍 Thank you for the quick response!

**Comment by acrisci** [comment]
This is very concerning to me. Most of my tags contained hyphens and now most of my tags are bad.

**Comment by joowani** [comment]
Hi acrisci,

Sorry to have inconvenienced you acrisci, what I can do is allow the hyphen but the shell variables will not be created. Would that be ok with you?

**Comment by acrisci** [comment]
What about changing hyphens to underscores in the shell variables? so `some-dir` becomes `$some_dir`.

**Comment by joowani** [comment]
Hmm I don't like making decisions for users but I think your idea is the best we've got. I will go ahead and make the changes (I hope you didn't lose your tags).

**Comment by joowani** [comment]
I've made a new release https://github.com/joowani/dtags/releases/tag/3.0.2. Hyphens are now replaced with underscores when shell variables are created. Sorry again for the inconvenience!

**Comment by acrisci** [comment]
:+1:
