### ISSUE TITLE
Problem about dtags

### ISSUE THREAD

**Issue by StSphinx** [joowani/dtags#16]
CentOS 7 
dtags 3.1.0

An error occurs as follows:

[root@node01 ~]# dtags
Traceback (most recent call last):
  File "/usr/bin/dtags", line 7, in <module>
    from dtags.commands.manage import main
ImportError: No module named manage

[root@node01 ~]# t /usr/bin bin
-bash: t: command not found

How can I deal with this?thx..

**Comment by joowani** [comment]
Hi StSphinx,

Just a few questions:
Have you added the one of the following lines to your shell config (if bash, ~/.bashrc)? 

```
# For zsh, place in ~/.zshrc:
command -v dtags-activate > /dev/null 2>&1 && eval "`dtags-activate zsh`"

# For bash, place in ~/.bashrc (or ~/.bash_profile for OS X):
command -v dtags-activate > /dev/null 2>&1 && eval "`dtags-activate bash`"

# For fish, place in ~/.config/fish/config.fish:
command -v dtags-activate > /dev/null 2>&1; and dtags-activate fish | source
```

Also are you upgrading from a lower version, or is this a fresh install?
Thanks

**Comment by joowani** [comment]
Hi StSphinx,

I have not heard back from you for a while so I will be closing this ticket for now.
I have a feeling that you were upgrading from an older version and somehow the previous executables did not get cleaned up properly.

Please try the following:
```
rm -f /usr/bin/dtags /usr/bin/tag  /usr/bin/tags  /usr/bin/untag /usr/bin/e
pip uninstall dtags
pip install dtags
```
If you have any virtualenvs do the same thing but replace `/usr/bin` with your virtualenv's bin directory.
Also remember to put the afforementioned line in your ~/.bashrc

Feel free to reopen this if you have any more issues.
Thanks!

**Comment by StSphinx** [comment]
Thanks for you help and tools.It's really beautiful and effective.
I tried many times on several machines.I think I get the point that the python has been updated and the path also has been changed so that the shell can't find the command.
e.g.
my python path is :  /usr/local/python2.7.11/
so dtags has been installed path : /usr/local/python2.7.11/bin/
Then, when I use  /usr/local/python2.7.11/bin/dtags-t
It worked as below:
Usage:
  t <dir> [<tag>...]
  t --help
  t --version

Arguments:
  dir     The directory path
  tag     The directory tag

**Comment by joowani** [comment]
Hi StSphinx,

First of all, thanks for liking dtags!
Instead of copying the file, you can add  `/usr/local/python2.7.11/bin` to your $PATH.
For example, in your `~/.bashrc` (or `~/.bash_profile`) you can add a line like this:

```
export PATH="$PATH:/usr/local/python2.7.11/bin" 
```
And then restart your shell.
Let me know if that works for you.

Thanks,
Jay

**Comment by StSphinx** [comment]
Hi joowani,

It also worked with following your operation.

Thanks.

**Comment by joowani** [comment]
No problem! Let me know if you have any other problems.
