### ISSUE TITLE
support tagging of paths containing `#`

### ISSUE THREAD

**Issue by evandrix** [joowani/dtags#17]
...instead of the error msg: `t: directory path .../#.../... contains bad characters #`
when `t .../\#.../... tag1 is run`

**Comment by joowani** [comment]
Hi evandrix,
 
I made a new release 3.2.0 which should now support the `#` character.
Please note that since linux variable names don't allow the `#` character so it has to be replaced by an `_` (underscore). Thanks.

Joohwan
