### ISSUE TITLE
Needs clarification for Windows users

### ISSUE THREAD

**Issue by bimlas** [joowani/dtags#19]
I would like to try out the stuff, but it simply does nothing on Windows 7, but drops the following message for example on `dtags-t`:

```
Traceback (most recent call last):
  File "C:\app\python3\Scripts\dtags-t-script.py", line 11, in <module>
    load_entry_point('dtags==3.2.1', 'console_scripts', 'dtags-t')()
  File "c:\app\python3\lib\site-packages\dtags\commands\t.py", line 30, in main
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
AttributeError: module 'signal' has no attribute 'SIGPIPE'
```

Googled for the answer and it seems that `SIGPIPE` does not exist on Win.

As the README says:

> `p` is currently not fully supported on Windows

I assume that you can try out on Win, but if I'm right, it has to be running in Cygwin (Git-Bash doesn't work too).

Is it possible to run in native `cmd.exe`? If not, then please write it to the documentation.

**Comment by joowani** [comment]
Hi @bimlas 

Unfortunately dtags is not supported on windows (I will make a note of it in the readme and the documentation). I should be able to fix the particular error you showed me, but there will things that won't work at least for the time being like the `p` command.

Thanks,
Joohwan

**Comment by joowani** [comment]
Hi @bimlas 

I took a look at the issue and it seems missing SIGPIPE is not the only problem. So it won't be a quick fix as I thought originally. Although I cannot commit to any timelines, I will revisit the windows compatibility issue in the future. For now I've edited the documentation to make it clear that Windows is not supported at the moment. You can always try dtags with [Bash on Ubuntu on Windows 10](https://msdn.microsoft.com/en-us/commandline/wsl/about).

Thanks,
Joohwan
