### ISSUE TITLE
`run`: can it be made to run in the context of $whoami's $SHELL + .rc file?

### ISSUE THREAD

**Issue by evandrix** [joowani/dtags#2]
suppose I have aliased `g p` => `git pull`

then
$ `tag folder1 @tag1 folder2 folder3 @tag23; run @tag23 g p`

```
folder2 (@tag23):
/bin/sh: g: command not found

folder3 (@tag23):
/bin/sh: g: command not found
```

can `run` be made to execute in my ($whoami) context, i.e. $SHELL (`zsh`) + my .rc (`.zshrc`) file?

**Comment by joowani** [comment]
Hi evandrix,

Currently I am looking for a way to execute the commands through the shell in interactive mode to retain all linux aliases. Once I do Ill include it in the next release. Thanks!

Jay

**Comment by joowani** [comment]
Hi again, 

I've pushed release 1.0.9. You should be able to use all your aliases defined in $SHELL.

Jay
