### ISSUE TITLE
d "directory" giving errors

### ISSUE THREAD

**Issue by muralikodali** [joowani/dtags#20]
after fish shell upgrade to version 3.0 , dtags giving error like this.

math: Error: Missing operator
'1 > 1'
   ^
math: Error: Missing operator
'1 < 1'
   ^
math: Error: Missing operator
'2 == 0'
   ^
math: Error: Missing operator
'2 == 1'
   ^

**Comment by swsnider** [comment]
This is because the use of `math` in these conditionals was apparently never really supposed to be supported -- they dropped that capability in fish > 3:

https://github.com/fish-shell/fish-shell/issues/4777

**Comment by swsnider** [comment]
See #21

**Comment by joowani** [comment]
Sorry for the late response @swsnider.

The changes are merged and a new release 3.2.4 is now out.
