### ISSUE TITLE
all commads can be used normally,but when use 'd' with error: command not found

### ISSUE THREAD

**Issue by yanzisucheng** [joowani/dtags#7]
MAC，after install ，finished configure bash_profile, all commads can be used normally,but when use 'd' with error.

**Comment by joowani** [comment]
Hi yanizsucheng,

That means somehow the output `dtags shell bash` is not being sourced properly.
Did you try restarting your shell? Perhaps you configured your environment so that ~/.bash_profile is not sourced at startup? If you have ~/.bashrc try putting the line in that file instead and restart your shell.

**Comment by joowani** [comment]
Assuming that this was just a sourcing issue I will close the issue for now. Let me know if anything else comes up!

**Comment by yanzisucheng** [comment]
I try configuring  "command -v dtags > /dev/null 2>&1 && . <(dtags shell bash)"  in ~/.bashrc ,then restart shell ,but still nothing happened.The same as before: "dtags list" can be used,"d" with error .
  
as:

$ cat ~/.bash_profile
export PATH=${PATH}:/Users/admin/Downloads/android-sdk-macosx/tools:/Users/admin/Downloads/android-sdk-macosx/platform-tools
export ANDROID_HOME="/Users/admin/Downloads/android-sdk-macosx"
source ~/.bashrc
command -v dtags > /dev/null 2>&1 && . <(dtags shell bash)
export NDK_HOME=/Users/admin/Downloads/android-ndk-r11-darwin-x86_64.tar.bz2
export PATH=$PATH:$NDK_HOME
$ dtags list
/Users/admin/Desktop/HR_ios #hr
$ d
-bash: d: command not found

**Comment by joowani** [comment]
Hmm that is strange. Could you please tell me the version of dtags you are using? Also what is the output of `dtags shell bash`? Are you 100% sure your `~/.bash_profile` is being sourced when the shell is started? Try running `dtags shell bash` and putting ouput directly in your `~/.bash_profile`.

**Comment by ethanfrogers** [comment]
I am also having this issue. I've copy and pasted the the output of `dtags shell bash` into my `~/.bash_profile` and the command worked as expected. I am on 2.0.3.

**Comment by joowani** [comment]
Hi ethanfrogers,

I am having a hard time reproducing this issue.
Could you try removing the check and put just `. <(dtags shell bash)`? Thanks.

**Comment by yanzisucheng** [comment]
as @ethanfrogers  commented.I am also on 2.0.3 and when  pasted the the output of dtags shell bash into my ~/.bash_profile , the command worked also as expected. I am sure that I have succeeded with configuration of ~/.bash_profile. I try put  . <(dtags shell bash) in my ~/.bash_profile,also failed that no command.

os x EI caption 
intall via 'pip'

**Comment by joowani** [comment]
Hello,

I've looked into this issue a bit more and it could be that /dev/fd is not available in your systems. 
Instead of `source <(dtags shell bash)`, could you try ``eval "`dtags shell bash`"``? Thanks for your patience.

**Comment by yanzisucheng** [comment]
Hi joowani,

thanks for your help !  use eval "`dtags shell bash`"  have solve  the problem. 

I think maybe more than a few people appear this issue, because when  I use my colleague‘s computer lastweek, the problem also occurs.
but anyway,the issue is fix now.
thanks !

**Comment by joowani** [comment]
No problem! I will update the README to reflect this case.
